// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZA0Qvp5d4RC6WEm_Gof3hSVMz82xe08c',
    appId: '1:852005782893:web:65356cd1da82de22e78664',
    messagingSenderId: '852005782893',
    projectId: 'cmsc23-mini-project',
    authDomain: 'cmsc23-mini-project.firebaseapp.com',
    storageBucket: 'cmsc23-mini-project.appspot.com',
    measurementId: 'G-W5FY12ER5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtO9kN-BJC1N_Exjdcu4MBbsjRhPVpcaA',
    appId: '1:852005782893:android:2f45b555f167c1b7e78664',
    messagingSenderId: '852005782893',
    projectId: 'cmsc23-mini-project',
    storageBucket: 'cmsc23-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_baftGLwvbPkhdxs77UfhmWG6MT5DmGA',
    appId: '1:852005782893:ios:36f421f4f238a0e8e78664',
    messagingSenderId: '852005782893',
    projectId: 'cmsc23-mini-project',
    storageBucket: 'cmsc23-mini-project.appspot.com',
    iosBundleId: 'com.example.exer5App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_baftGLwvbPkhdxs77UfhmWG6MT5DmGA',
    appId: '1:852005782893:ios:36f421f4f238a0e8e78664',
    messagingSenderId: '852005782893',
    projectId: 'cmsc23-mini-project',
    storageBucket: 'cmsc23-mini-project.appspot.com',
    iosBundleId: 'com.example.exer5App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZA0Qvp5d4RC6WEm_Gof3hSVMz82xe08c',
    appId: '1:852005782893:web:17589bdac8545102e78664',
    messagingSenderId: '852005782893',
    projectId: 'cmsc23-mini-project',
    authDomain: 'cmsc23-mini-project.firebaseapp.com',
    storageBucket: 'cmsc23-mini-project.appspot.com',
    measurementId: 'G-GCBMH6WEJC',
  );
}
