// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-tCpQ_lasKiLyNR5u8xbBNV5VL9o0D0g',
    appId: '1:318346832538:web:6cd0de0a3d4a01daeb4d23',
    messagingSenderId: '318346832538',
    projectId: 'exer7-slambook-firebase',
    authDomain: 'exer7-slambook-firebase.firebaseapp.com',
    storageBucket: 'exer7-slambook-firebase.appspot.com',
    measurementId: 'G-K4PRD0SS2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2pELlY7pcDD5mythuE8f46lI6zAos6e4',
    appId: '1:318346832538:android:b89be92fc859bbbfeb4d23',
    messagingSenderId: '318346832538',
    projectId: 'exer7-slambook-firebase',
    storageBucket: 'exer7-slambook-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1q-xV8b2mcc09NMYCKFPVdmqBR58G14o',
    appId: '1:318346832538:ios:da95cb5faf4cc404eb4d23',
    messagingSenderId: '318346832538',
    projectId: 'exer7-slambook-firebase',
    storageBucket: 'exer7-slambook-firebase.appspot.com',
    iosBundleId: 'com.example.exer5App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1q-xV8b2mcc09NMYCKFPVdmqBR58G14o',
    appId: '1:318346832538:ios:da95cb5faf4cc404eb4d23',
    messagingSenderId: '318346832538',
    projectId: 'exer7-slambook-firebase',
    storageBucket: 'exer7-slambook-firebase.appspot.com',
    iosBundleId: 'com.example.exer5App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-tCpQ_lasKiLyNR5u8xbBNV5VL9o0D0g',
    appId: '1:318346832538:web:b85905f88121ff8feb4d23',
    messagingSenderId: '318346832538',
    projectId: 'exer7-slambook-firebase',
    authDomain: 'exer7-slambook-firebase.firebaseapp.com',
    storageBucket: 'exer7-slambook-firebase.appspot.com',
    measurementId: 'G-N9YWBSEMM1',
  );
}
